# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import common.post_grpc.content_pb2 as content__pb2


class ContentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePost = channel.unary_unary(
                '/Content/CreatePost',
                request_serializer=content__pb2.CreatePostRequest.SerializeToString,
                response_deserializer=content__pb2.ChangePostReply.FromString,
                )
        self.UpdatePost = channel.unary_unary(
                '/Content/UpdatePost',
                request_serializer=content__pb2.UpdatePostRequest.SerializeToString,
                response_deserializer=content__pb2.ChangePostReply.FromString,
                )
        self.DeletePost = channel.unary_unary(
                '/Content/DeletePost',
                request_serializer=content__pb2.DeletePostRequest.SerializeToString,
                response_deserializer=content__pb2.ChangePostReply.FromString,
                )
        self.GetPost = channel.unary_unary(
                '/Content/GetPost',
                request_serializer=content__pb2.GetPostRequest.SerializeToString,
                response_deserializer=content__pb2.GetPostReply.FromString,
                )
        self.GetPosts = channel.unary_stream(
                '/Content/GetPosts',
                request_serializer=content__pb2.GetPostsRequest.SerializeToString,
                response_deserializer=content__pb2.GetPostReply.FromString,
                )


class ContentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPosts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePost,
                    request_deserializer=content__pb2.CreatePostRequest.FromString,
                    response_serializer=content__pb2.ChangePostReply.SerializeToString,
            ),
            'UpdatePost': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePost,
                    request_deserializer=content__pb2.UpdatePostRequest.FromString,
                    response_serializer=content__pb2.ChangePostReply.SerializeToString,
            ),
            'DeletePost': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePost,
                    request_deserializer=content__pb2.DeletePostRequest.FromString,
                    response_serializer=content__pb2.ChangePostReply.SerializeToString,
            ),
            'GetPost': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPost,
                    request_deserializer=content__pb2.GetPostRequest.FromString,
                    response_serializer=content__pb2.GetPostReply.SerializeToString,
            ),
            'GetPosts': grpc.unary_stream_rpc_method_handler(
                    servicer.GetPosts,
                    request_deserializer=content__pb2.GetPostsRequest.FromString,
                    response_serializer=content__pb2.GetPostReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Content', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Content(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Content/CreatePost',
            content__pb2.CreatePostRequest.SerializeToString,
            content__pb2.ChangePostReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Content/UpdatePost',
            content__pb2.UpdatePostRequest.SerializeToString,
            content__pb2.ChangePostReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletePost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Content/DeletePost',
            content__pb2.DeletePostRequest.SerializeToString,
            content__pb2.ChangePostReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Content/GetPost',
            content__pb2.GetPostRequest.SerializeToString,
            content__pb2.GetPostReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPosts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Content/GetPosts',
            content__pb2.GetPostsRequest.SerializeToString,
            content__pb2.GetPostReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
