openapi: 3.1.0
info:
  title: Social Network API
  version: 0.1.0
paths:
  /user:
    put:
      summary: Update user info
      operationId: update_info_user_put
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Body_update_info_user_put'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    post:
      summary: Create new user
      operationId: create_user_user_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterData'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /user_authentication:
    post:
      summary: Аутентификация в системе по логину и паролю
      operationId: authenticate_user_user_authentication_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterData'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionKey'
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    Body_update_info_user_put:
      properties:
        user_data:
          $ref: '#/components/schemas/UserUpdate'
        session_key:
          $ref: '#/components/schemas/SessionKey'
      type: object
      required:
        - user_data
        - session_key
      title: Body_update_info_user_put
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    RegisterData:
      properties:
        login:
          type: string
          title: Login
        password:
          type: string
          title: Password
      type: object
      required:
        - login
        - password
      title: RegisterData
    SessionKey:
      properties:
        key:
          type: string
          format: uuid
          title: Key
      type: object
      required:
        - key
      title: SessionKey
    UserUpdate:
      properties:
        login:
          type: string
          title: Login
        name:
          anyOf:
            - type: string
            - type: 'null'
          title: Name
        surname:
          anyOf:
            - type: string
            - type: 'null'
          title: Surname
        birthdate:
          anyOf:
            - type: string
              format: date
            - type: 'null'
          title: Birthdate
        mail:
          anyOf:
            - type: string
            - type: 'null'
          title: Mail
        number_phone:
          anyOf:
            - type: string
            - type: 'null'
          title: Number Phone
      type: object
      required:
        - login
      title: UserUpdate
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
        - loc
        - msg
        - type
      title: ValidationError
